<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opensergo/proto/service_contract/v1/service_contract.proto

namespace Opensergo\Proto\Service_contract\V1;

if (false) {
    /**
     * This class is deprecated. Use Opensergo\Proto\Service_contract\V1\FieldDescriptor\Label instead.
     * @deprecated
     */
    class FieldDescriptor_Label {}
}
class_exists(FieldDescriptor\Label::class);
@trigger_error('Opensergo\Proto\Service_contract\V1\FieldDescriptor_Label is deprecated and will be removed in the next major release. Use Opensergo\Proto\Service_contract\V1\FieldDescriptor\Label instead', E_USER_DEPRECATED);

