<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opensergo/proto/service_contract/v1/service_contract.proto

namespace Opensergo\Proto\Service_contract\V1;

if (false) {
    /**
     * This class is deprecated. Use Opensergo\Proto\Service_contract\V1\FieldDescriptor\Type instead.
     * @deprecated
     */
    class FieldDescriptor_Type {}
}
class_exists(FieldDescriptor\Type::class);
@trigger_error('Opensergo\Proto\Service_contract\V1\FieldDescriptor_Type is deprecated and will be removed in the next major release. Use Opensergo\Proto\Service_contract\V1\FieldDescriptor\Type instead', E_USER_DEPRECATED);

