<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opensergo/proto/service_contract/v1/service_contract.proto

namespace Opensergo\Proto\Service_contract\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Describes a method of a service.
 *
 * Generated from protobuf message <code>opensergo.proto.service_contract.v1.MethodDescriptor</code>
 */
class MethodDescriptor extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * Input and output type names.  These are resolved in the same way as
     * FieldDescriptor.type_name, but must refer to a message type.
     *
     * Generated from protobuf field <code>repeated string input_types = 2;</code>
     */
    private $input_types;
    /**
     * Generated from protobuf field <code>repeated string output_types = 3;</code>
     */
    private $output_types;
    /**
     * Identifies if client streams multiple client messages
     *
     * Generated from protobuf field <code>optional bool client_streaming = 5;</code>
     */
    protected $client_streaming = null;
    /**
     * Identifies if server streams multiple server messages
     *
     * Generated from protobuf field <code>optional bool server_streaming = 6;</code>
     */
    protected $server_streaming = null;
    /**
     * description of this method
     *
     * Generated from protobuf field <code>optional string description = 7;</code>
     */
    protected $description = null;
    /**
     * Generated from protobuf field <code>repeated string http_paths = 8;</code>
     */
    private $http_paths;
    /**
     * Generated from protobuf field <code>repeated string http_methods = 9;</code>
     */
    private $http_methods;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $input_types
     *           Input and output type names.  These are resolved in the same way as
     *           FieldDescriptor.type_name, but must refer to a message type.
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $output_types
     *     @type bool $client_streaming
     *           Identifies if client streams multiple client messages
     *     @type bool $server_streaming
     *           Identifies if server streams multiple server messages
     *     @type string $description
     *           description of this method
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $http_paths
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $http_methods
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Opensergo\Proto\ServiceContract\V1\ServiceContract::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Input and output type names.  These are resolved in the same way as
     * FieldDescriptor.type_name, but must refer to a message type.
     *
     * Generated from protobuf field <code>repeated string input_types = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getInputTypes()
    {
        return $this->input_types;
    }

    /**
     * Input and output type names.  These are resolved in the same way as
     * FieldDescriptor.type_name, but must refer to a message type.
     *
     * Generated from protobuf field <code>repeated string input_types = 2;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setInputTypes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->input_types = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string output_types = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getOutputTypes()
    {
        return $this->output_types;
    }

    /**
     * Generated from protobuf field <code>repeated string output_types = 3;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setOutputTypes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->output_types = $arr;

        return $this;
    }

    /**
     * Identifies if client streams multiple client messages
     *
     * Generated from protobuf field <code>optional bool client_streaming = 5;</code>
     * @return bool
     */
    public function getClientStreaming()
    {
        return isset($this->client_streaming) ? $this->client_streaming : false;
    }

    public function hasClientStreaming()
    {
        return isset($this->client_streaming);
    }

    public function clearClientStreaming()
    {
        unset($this->client_streaming);
    }

    /**
     * Identifies if client streams multiple client messages
     *
     * Generated from protobuf field <code>optional bool client_streaming = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setClientStreaming($var)
    {
        GPBUtil::checkBool($var);
        $this->client_streaming = $var;

        return $this;
    }

    /**
     * Identifies if server streams multiple server messages
     *
     * Generated from protobuf field <code>optional bool server_streaming = 6;</code>
     * @return bool
     */
    public function getServerStreaming()
    {
        return isset($this->server_streaming) ? $this->server_streaming : false;
    }

    public function hasServerStreaming()
    {
        return isset($this->server_streaming);
    }

    public function clearServerStreaming()
    {
        unset($this->server_streaming);
    }

    /**
     * Identifies if server streams multiple server messages
     *
     * Generated from protobuf field <code>optional bool server_streaming = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setServerStreaming($var)
    {
        GPBUtil::checkBool($var);
        $this->server_streaming = $var;

        return $this;
    }

    /**
     * description of this method
     *
     * Generated from protobuf field <code>optional string description = 7;</code>
     * @return string
     */
    public function getDescription()
    {
        return isset($this->description) ? $this->description : '';
    }

    public function hasDescription()
    {
        return isset($this->description);
    }

    public function clearDescription()
    {
        unset($this->description);
    }

    /**
     * description of this method
     *
     * Generated from protobuf field <code>optional string description = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string http_paths = 8;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getHttpPaths()
    {
        return $this->http_paths;
    }

    /**
     * Generated from protobuf field <code>repeated string http_paths = 8;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setHttpPaths($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->http_paths = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string http_methods = 9;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getHttpMethods()
    {
        return $this->http_methods;
    }

    /**
     * Generated from protobuf field <code>repeated string http_methods = 9;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setHttpMethods($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->http_methods = $arr;

        return $this;
    }

}

