<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opensergo/proto/service_contract/v1/service_contract.proto

namespace Opensergo\Proto\Service_contract\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>opensergo.proto.service_contract.v1.ReportMetadataRequest</code>
 */
class ReportMetadataRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string app_name = 1;</code>
     */
    protected $app_name = '';
    /**
     * Generated from protobuf field <code>.opensergo.proto.service_contract.v1.Node node = 2;</code>
     */
    protected $node = null;
    /**
     * Generated from protobuf field <code>repeated .opensergo.proto.service_contract.v1.ServiceMetadata service_metadata = 3;</code>
     */
    private $service_metadata;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $app_name
     *     @type \Opensergo\Proto\Service_contract\V1\Node $node
     *     @type \Opensergo\Proto\Service_contract\V1\ServiceMetadata[]|\Google\Protobuf\Internal\RepeatedField $service_metadata
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Opensergo\Proto\ServiceContract\V1\ServiceContract::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string app_name = 1;</code>
     * @return string
     */
    public function getAppName()
    {
        return $this->app_name;
    }

    /**
     * Generated from protobuf field <code>string app_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAppName($var)
    {
        GPBUtil::checkString($var, True);
        $this->app_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.opensergo.proto.service_contract.v1.Node node = 2;</code>
     * @return \Opensergo\Proto\Service_contract\V1\Node|null
     */
    public function getNode()
    {
        return $this->node;
    }

    public function hasNode()
    {
        return isset($this->node);
    }

    public function clearNode()
    {
        unset($this->node);
    }

    /**
     * Generated from protobuf field <code>.opensergo.proto.service_contract.v1.Node node = 2;</code>
     * @param \Opensergo\Proto\Service_contract\V1\Node $var
     * @return $this
     */
    public function setNode($var)
    {
        GPBUtil::checkMessage($var, \Opensergo\Proto\Service_contract\V1\Node::class);
        $this->node = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .opensergo.proto.service_contract.v1.ServiceMetadata service_metadata = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getServiceMetadata()
    {
        return $this->service_metadata;
    }

    /**
     * Generated from protobuf field <code>repeated .opensergo.proto.service_contract.v1.ServiceMetadata service_metadata = 3;</code>
     * @param \Opensergo\Proto\Service_contract\V1\ServiceMetadata[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setServiceMetadata($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Opensergo\Proto\Service_contract\V1\ServiceMetadata::class);
        $this->service_metadata = $arr;

        return $this;
    }

}

