<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opensergo/proto/service_contract/v1/service_contract.proto

namespace Opensergo\Proto\Service_contract\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>opensergo.proto.service_contract.v1.ServiceContract</code>
 */
class ServiceContract extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .opensergo.proto.service_contract.v1.ServiceDescriptor services = 1;</code>
     */
    private $services;
    /**
     * Generated from protobuf field <code>repeated .opensergo.proto.service_contract.v1.TypeDescriptor types = 2;</code>
     */
    private $types;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Opensergo\Proto\Service_contract\V1\ServiceDescriptor[]|\Google\Protobuf\Internal\RepeatedField $services
     *     @type \Opensergo\Proto\Service_contract\V1\TypeDescriptor[]|\Google\Protobuf\Internal\RepeatedField $types
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Opensergo\Proto\ServiceContract\V1\ServiceContract::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .opensergo.proto.service_contract.v1.ServiceDescriptor services = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getServices()
    {
        return $this->services;
    }

    /**
     * Generated from protobuf field <code>repeated .opensergo.proto.service_contract.v1.ServiceDescriptor services = 1;</code>
     * @param \Opensergo\Proto\Service_contract\V1\ServiceDescriptor[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setServices($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Opensergo\Proto\Service_contract\V1\ServiceDescriptor::class);
        $this->services = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .opensergo.proto.service_contract.v1.TypeDescriptor types = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTypes()
    {
        return $this->types;
    }

    /**
     * Generated from protobuf field <code>repeated .opensergo.proto.service_contract.v1.TypeDescriptor types = 2;</code>
     * @param \Opensergo\Proto\Service_contract\V1\TypeDescriptor[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTypes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Opensergo\Proto\Service_contract\V1\TypeDescriptor::class);
        $this->types = $arr;

        return $this;
    }

}

