<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opensergo/proto/service_contract/v1/service_contract.proto

namespace Opensergo\Proto\Service_contract\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Define services on same address and port
 *
 * Generated from protobuf message <code>opensergo.proto.service_contract.v1.ServiceMetadata</code>
 */
class ServiceMetadata extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .opensergo.proto.service_contract.v1.SocketAddress listening_addresses = 1;</code>
     */
    private $listening_addresses;
    /**
     * Generated from protobuf field <code>repeated string protocols = 2;</code>
     */
    private $protocols;
    /**
     * Generated from protobuf field <code>.opensergo.proto.service_contract.v1.ServiceContract service_contract = 3;</code>
     */
    protected $service_contract = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Opensergo\Proto\Service_contract\V1\SocketAddress[]|\Google\Protobuf\Internal\RepeatedField $listening_addresses
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $protocols
     *     @type \Opensergo\Proto\Service_contract\V1\ServiceContract $service_contract
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Opensergo\Proto\ServiceContract\V1\ServiceContract::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .opensergo.proto.service_contract.v1.SocketAddress listening_addresses = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getListeningAddresses()
    {
        return $this->listening_addresses;
    }

    /**
     * Generated from protobuf field <code>repeated .opensergo.proto.service_contract.v1.SocketAddress listening_addresses = 1;</code>
     * @param \Opensergo\Proto\Service_contract\V1\SocketAddress[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setListeningAddresses($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Opensergo\Proto\Service_contract\V1\SocketAddress::class);
        $this->listening_addresses = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string protocols = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getProtocols()
    {
        return $this->protocols;
    }

    /**
     * Generated from protobuf field <code>repeated string protocols = 2;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setProtocols($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->protocols = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.opensergo.proto.service_contract.v1.ServiceContract service_contract = 3;</code>
     * @return \Opensergo\Proto\Service_contract\V1\ServiceContract|null
     */
    public function getServiceContract()
    {
        return $this->service_contract;
    }

    public function hasServiceContract()
    {
        return isset($this->service_contract);
    }

    public function clearServiceContract()
    {
        unset($this->service_contract);
    }

    /**
     * Generated from protobuf field <code>.opensergo.proto.service_contract.v1.ServiceContract service_contract = 3;</code>
     * @param \Opensergo\Proto\Service_contract\V1\ServiceContract $var
     * @return $this
     */
    public function setServiceContract($var)
    {
        GPBUtil::checkMessage($var, \Opensergo\Proto\Service_contract\V1\ServiceContract::class);
        $this->service_contract = $var;

        return $this;
    }

}

