<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opensergo/proto/service_contract/v1/service_contract.proto

namespace Opensergo\Proto\Service_contract\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>opensergo.proto.service_contract.v1.SocketAddress</code>
 */
class SocketAddress extends \Google\Protobuf\Internal\Message
{
    /**
     * The address for this socket.
     * This address shouldn't be 0.0.0.0/127.0.0.1, because those cannot identity
     * or access from external
     *
     * Generated from protobuf field <code>string address = 1;</code>
     */
    protected $address = '';
    /**
     * Generated from protobuf field <code>uint32 port_value = 2;</code>
     */
    protected $port_value = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $address
     *           The address for this socket.
     *           This address shouldn't be 0.0.0.0/127.0.0.1, because those cannot identity
     *           or access from external
     *     @type int $port_value
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Opensergo\Proto\ServiceContract\V1\ServiceContract::initOnce();
        parent::__construct($data);
    }

    /**
     * The address for this socket.
     * This address shouldn't be 0.0.0.0/127.0.0.1, because those cannot identity
     * or access from external
     *
     * Generated from protobuf field <code>string address = 1;</code>
     * @return string
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     * The address for this socket.
     * This address shouldn't be 0.0.0.0/127.0.0.1, because those cannot identity
     * or access from external
     *
     * Generated from protobuf field <code>string address = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 port_value = 2;</code>
     * @return int
     */
    public function getPortValue()
    {
        return $this->port_value;
    }

    /**
     * Generated from protobuf field <code>uint32 port_value = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setPortValue($var)
    {
        GPBUtil::checkUint32($var);
        $this->port_value = $var;

        return $this;
    }

}

