<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opensergo/proto/service_contract/v1/service_contract.proto

namespace Opensergo\Proto\Service_contract\V1;

if (false) {
    /**
     * This class is deprecated. Use Opensergo\Proto\Service_contract\V1\TypeDescriptor\ReservedRange instead.
     * @deprecated
     */
    class TypeDescriptor_ReservedRange {}
}
class_exists(TypeDescriptor\ReservedRange::class);
@trigger_error('Opensergo\Proto\Service_contract\V1\TypeDescriptor_ReservedRange is deprecated and will be removed in the next major release. Use Opensergo\Proto\Service_contract\V1\TypeDescriptor\ReservedRange instead', E_USER_DEPRECATED);

