<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opensergo/proto/service_contract/v1/service_contract.proto

namespace Opensergo\Proto\Service_contract\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Describes a message type.
 *
 * Generated from protobuf message <code>opensergo.proto.service_contract.v1.TypeDescriptor</code>
 */
class TypeDescriptor extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>repeated .opensergo.proto.service_contract.v1.FieldDescriptor fields = 2;</code>
     */
    private $fields;
    /**
     * Generated from protobuf field <code>optional .opensergo.proto.service_contract.v1.MessageOptions options = 7;</code>
     */
    protected $options = null;
    /**
     * Generated from protobuf field <code>repeated .opensergo.proto.service_contract.v1.TypeDescriptor.ReservedRange reserved_range = 9;</code>
     */
    private $reserved_range;
    /**
     * Reserved field names, which may not be used by fields in the same message.
     * A given name may only be reserved once.
     *
     * Generated from protobuf field <code>repeated string reserved_name = 10;</code>
     */
    private $reserved_name;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *     @type \Opensergo\Proto\Service_contract\V1\FieldDescriptor[]|\Google\Protobuf\Internal\RepeatedField $fields
     *     @type \Opensergo\Proto\Service_contract\V1\MessageOptions $options
     *     @type \Opensergo\Proto\Service_contract\V1\TypeDescriptor\ReservedRange[]|\Google\Protobuf\Internal\RepeatedField $reserved_range
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $reserved_name
     *           Reserved field names, which may not be used by fields in the same message.
     *           A given name may only be reserved once.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Opensergo\Proto\ServiceContract\V1\ServiceContract::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .opensergo.proto.service_contract.v1.FieldDescriptor fields = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFields()
    {
        return $this->fields;
    }

    /**
     * Generated from protobuf field <code>repeated .opensergo.proto.service_contract.v1.FieldDescriptor fields = 2;</code>
     * @param \Opensergo\Proto\Service_contract\V1\FieldDescriptor[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFields($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Opensergo\Proto\Service_contract\V1\FieldDescriptor::class);
        $this->fields = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .opensergo.proto.service_contract.v1.MessageOptions options = 7;</code>
     * @return \Opensergo\Proto\Service_contract\V1\MessageOptions|null
     */
    public function getOptions()
    {
        return $this->options;
    }

    public function hasOptions()
    {
        return isset($this->options);
    }

    public function clearOptions()
    {
        unset($this->options);
    }

    /**
     * Generated from protobuf field <code>optional .opensergo.proto.service_contract.v1.MessageOptions options = 7;</code>
     * @param \Opensergo\Proto\Service_contract\V1\MessageOptions $var
     * @return $this
     */
    public function setOptions($var)
    {
        GPBUtil::checkMessage($var, \Opensergo\Proto\Service_contract\V1\MessageOptions::class);
        $this->options = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .opensergo.proto.service_contract.v1.TypeDescriptor.ReservedRange reserved_range = 9;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getReservedRange()
    {
        return $this->reserved_range;
    }

    /**
     * Generated from protobuf field <code>repeated .opensergo.proto.service_contract.v1.TypeDescriptor.ReservedRange reserved_range = 9;</code>
     * @param \Opensergo\Proto\Service_contract\V1\TypeDescriptor\ReservedRange[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setReservedRange($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Opensergo\Proto\Service_contract\V1\TypeDescriptor\ReservedRange::class);
        $this->reserved_range = $arr;

        return $this;
    }

    /**
     * Reserved field names, which may not be used by fields in the same message.
     * A given name may only be reserved once.
     *
     * Generated from protobuf field <code>repeated string reserved_name = 10;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getReservedName()
    {
        return $this->reserved_name;
    }

    /**
     * Reserved field names, which may not be used by fields in the same message.
     * A given name may only be reserved once.
     *
     * Generated from protobuf field <code>repeated string reserved_name = 10;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setReservedName($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->reserved_name = $arr;

        return $this;
    }

}

