<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opensergo/proto/service_contract/v1/service_contract.proto

namespace Opensergo\Proto\Service_contract\V1;

if (false) {
    /**
     * This class is deprecated. Use Opensergo\Proto\Service_contract\V1\UninterpretedOption\NamePart instead.
     * @deprecated
     */
    class UninterpretedOption_NamePart {}
}
class_exists(UninterpretedOption\NamePart::class);
@trigger_error('Opensergo\Proto\Service_contract\V1\UninterpretedOption_NamePart is deprecated and will be removed in the next major release. Use Opensergo\Proto\Service_contract\V1\UninterpretedOption\NamePart instead', E_USER_DEPRECATED);

